import { expect, test, type Page } from '@playwright/test'
import path from 'node:path'
import {
  clearAndSeedWorkspace,
  createTestUserDataDir,
  launchApp,
  removePathWithRetry,
  testWorkspacePath,
} from './workspace-canvas.helpers'

async function readTaskLinkedAgentInfo(window: Page): Promise<{
  linkedAgentNodeId: string | null
  sessionId: string | null
  resumeSessionId: string | null
  resumeSessionIdVerified: boolean
}> {
  const raw = await window.evaluate(async () => {
    return await window.opencoveApi.persistence.readWorkspaceStateRaw()
  })

  if (!raw) {
    return {
      linkedAgentNodeId: null,
      sessionId: null,
      resumeSessionId: null,
      resumeSessionIdVerified: false,
    }
  }

  const parsed = JSON.parse(raw) as {
    workspaces?: Array<{
      nodes?: Array<{
        id?: string
        kind?: string
        sessionId?: string
        task?: { linkedAgentNodeId?: string | null } | null
        agent?: {
          resumeSessionId?: string | null
          resumeSessionIdVerified?: boolean
        } | null
      }>
    }>
  }

  const nodes = parsed.workspaces?.[0]?.nodes ?? []
  const task = nodes.find(node => node.kind === 'task')
  const linkedAgentNodeId = task?.task?.linkedAgentNodeId ?? null
  const agent = linkedAgentNodeId
    ? nodes.find(node => node.kind === 'agent' && node.id === linkedAgentNodeId)
    : null

  return {
    linkedAgentNodeId,
    sessionId:
      typeof agent?.sessionId === 'string' && agent.sessionId.trim().length > 0
        ? agent.sessionId
        : null,
    resumeSessionId: agent?.agent?.resumeSessionId ?? null,
    resumeSessionIdVerified: agent?.agent?.resumeSessionIdVerified ?? false,
  }
}

test.describe('Recovery - Agent placeholder click preserves history', () => {
  test('keeps restored history visible when a click first triggers control-only redraw output', async () => {
    const userDataDir = await createTestUserDataDir()
    const taskDirectory = path.join(testWorkspacePath, 'docs')

    try {
      const { electronApp, window } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: false,
        env: {
          OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
          OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-click-redraw-after-click',
        },
      })

      try {
        await clearAndSeedWorkspace(
          window,
          [
            {
              id: 'task-one',
              title: 'First task',
              position: { x: 120, y: 140 },
              width: 460,
              height: 280,
              kind: 'task',
              task: {
                requirement: 'Verify placeholder history survives click-triggered redraw on resume',
                status: 'todo',
                linkedAgentNodeId: null,
                lastRunAt: null,
                autoGeneratedTitle: false,
                createdAt: '2026-03-08T00:00:00.000Z',
                updatedAt: '2026-03-08T00:00:00.000Z',
              },
            },
          ],
          {
            settings: {
              defaultProvider: 'codex',
              customModelEnabledByProvider: {
                'claude-code': false,
                codex: true,
              },
              customModelByProvider: {
                'claude-code': '',
                codex: 'gpt-5.2-codex',
              },
              customModelOptionsByProvider: {
                'claude-code': [],
                codex: ['gpt-5.2-codex'],
              },
            },
            spaces: [
              {
                id: 'space-one',
                name: 'docs',
                directoryPath: taskDirectory,
                nodeIds: ['task-one'],
                rect: null,
              },
            ],
          },
        )

        await expect(window.locator('.task-node')).toHaveCount(1)
        await window.locator('.task-node [data-testid="task-node-run-agent"]').click()
        await expect(window.locator('.terminal-node')).toHaveCount(1)

        await expect
          .poll(async () => {
            const binding = await readTaskLinkedAgentInfo(window)
            return (
              typeof binding.linkedAgentNodeId === 'string' &&
              binding.linkedAgentNodeId.length > 0 &&
              binding.resumeSessionIdVerified === true &&
              typeof binding.resumeSessionId === 'string' &&
              binding.resumeSessionId.length > 0 &&
              typeof binding.sessionId === 'string' &&
              binding.sessionId.length > 0
            )
          })
          .toBe(true)

        const agentInfo = await readTaskLinkedAgentInfo(window)
        if (!agentInfo.linkedAgentNodeId || !agentInfo.sessionId) {
          throw new Error('Failed to resolve task-linked agent identifiers')
        }

        const snapshot = await window.evaluate(
          async payload => {
            const result = await window.opencoveApi.pty.snapshot({ sessionId: payload.sessionId })
            await window.opencoveApi.persistence.writeAgentNodePlaceholderScrollback({
              nodeId: payload.nodeId,
              scrollback: result.data,
            })
            return result.data
          },
          { nodeId: agentInfo.linkedAgentNodeId, sessionId: agentInfo.sessionId },
        )

        expect(snapshot).toContain('[opencove-test-click] ready')
      } finally {
        await electronApp.close()
      }

      const { electronApp: restartedApp, window: restartedWindow } = await launchApp({
        windowMode: 'offscreen',
        userDataDir,
        cleanupUserDataDir: true,
        env: {
          OPENCOVE_TEST_ENABLE_SESSION_STATE_WATCHER: '1',
          OPENCOVE_TEST_AGENT_SESSION_SCENARIO: 'codex-click-redraw-after-click',
        },
      })

      try {
        await expect(restartedWindow.locator('.task-node')).toHaveCount(1, { timeout: 30_000 })
        await expect(restartedWindow.locator('.terminal-node')).toHaveCount(1, { timeout: 30_000 })

        const agentNode = restartedWindow.locator('.terminal-node').first()
        const terminalBody = agentNode.locator('.xterm')
        const transcript = agentNode.locator('.terminal-node__transcript')

        await expect(agentNode).toContainText('[opencove-test-click] ready', { timeout: 10_000 })
        await expect(agentNode.locator('.terminal-node__terminal')).toHaveAttribute(
          'aria-busy',
          'false',
        )

        const transcriptBeforeClick = (await transcript.textContent()) ?? ''
        expect(transcriptBeforeClick).toContain('[opencove-test-click] ready')

        await terminalBody.click()
        await restartedWindow.waitForTimeout(200)

        const transcriptAfterControlOnlyRedraw = (await transcript.textContent()) ?? ''
        expect(transcriptAfterControlOnlyRedraw).toContain('[opencove-test-click] ready')
        expect(transcriptAfterControlOnlyRedraw).not.toContain(
          '[opencove-test-click] redraw complete',
        )

        await expect(transcript).toContainText('[opencove-test-click] redraw complete', {
          timeout: 5_000,
        })
        await expect(transcript).not.toContainText('[opencove-test-click] ready')
      } finally {
        await restartedApp.close()
      }
    } finally {
      await removePathWithRetry(userDataDir)
    }
  })
})
