import type { Node } from '@xyflow/react'
import type { AgentSettings, AgentProvider } from '../settings/agentConfig'

export type WorkspaceNodeKind = 'terminal' | 'agent' | 'task'

export type AgentRuntimeStatus = 'running' | 'exited' | 'failed' | 'stopped' | 'restoring'

export type TaskRuntimeStatus = 'todo' | 'doing' | 'ai_done' | 'done'

export type AgentLaunchMode = 'new' | 'resume'

export type ExecutionDirectoryMode = 'workspace' | 'custom'

export interface AgentNodeData {
  provider: AgentProvider
  prompt: string
  model: string | null
  effectiveModel: string | null
  launchMode: AgentLaunchMode
  resumeSessionId: string | null
  executionDirectory: string
  directoryMode: ExecutionDirectoryMode
  customDirectory: string | null
  shouldCreateDirectory: boolean
  taskId: string | null
}

export interface TaskNodeData {
  requirement: string
  status: TaskRuntimeStatus
  linkedAgentNodeId: string | null
  lastRunAt: string | null
  autoGeneratedTitle: boolean
}

export interface TerminalNodeData {
  [key: string]: unknown
  sessionId: string
  title: string
  width: number
  height: number
  kind: WorkspaceNodeKind
  status: AgentRuntimeStatus | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
  scrollback: string | null
  agent: AgentNodeData | null
  task: TaskNodeData | null
}

export interface WorkspaceState {
  id: string
  name: string
  path: string
  nodes: Node<TerminalNodeData>[]
}

export interface PersistedWorkspaceState {
  id: string
  name: string
  path: string
  nodes: PersistedTerminalNode[]
}

export interface PersistedTerminalNode {
  id: string
  title: string
  position: Point
  width: number
  height: number
  kind: WorkspaceNodeKind
  status: AgentRuntimeStatus | null
  startedAt: string | null
  endedAt: string | null
  exitCode: number | null
  lastError: string | null
  scrollback: string | null
  agent: AgentNodeData | null
  task: TaskNodeData | null
}

export interface PersistedAppState {
  activeWorkspaceId: string | null
  workspaces: PersistedWorkspaceState[]
  settings: AgentSettings
}

export interface Size {
  width: number
  height: number
}

export interface Point {
  x: number
  y: number
}
